import React, { useState } from 'react';
import { CustomerInquiry, InquiryStatus, SalonInfo, ServiceItem } from '../types';
import { Icon } from './Icon';

interface InquiriesManagerProps {
  inquiries: CustomerInquiry[];
  onUpdateInquiries: (updated: CustomerInquiry[]) => void;
  onShowNotification: (msg: string) => void;
  salonInfo: SalonInfo;
  services: ServiceItem[];
}

export const InquiriesManager: React.FC<InquiriesManagerProps> = ({
  inquiries,
  onUpdateInquiries,
  onShowNotification,
  salonInfo,
  services
}) => {
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [isSummaryModalOpen, setIsSummaryModalOpen] = useState(false);
  const [isAddManualOpen, setIsAddManualOpen] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);
  const [editingStaffNoteId, setEditingStaffNoteId] = useState<string | null>(null);
  const [staffNoteDraft, setStaffNoteDraft] = useState<string>('');

  // Target email requested by user
  const TARGET_EMAIL = 'kevfun73@gmail.com';
  const [summaryRecipient, setSummaryRecipient] = useState(TARGET_EMAIL);

  // Manual inquiry form state
  const [manualForm, setManualForm] = useState({
    fullName: '',
    phone: '',
    email: '',
    serviceId: services[0]?.id || 'womens-cut',
    preferredDate: '',
    preferredTime: '11:00 AM',
    notes: '',
    staffNotes: '',
    status: 'New' as InquiryStatus
  });

  // Calculate counts
  const totalCount = inquiries.length;
  const newCount = inquiries.filter(i => i.status === 'New').length;
  const contactedCount = inquiries.filter(i => i.status === 'Contacted').length;
  const confirmedCount = inquiries.filter(i => i.status === 'Confirmed').length;
  const completedCount = inquiries.filter(i => i.status === 'Completed').length;
  const archivedCount = inquiries.filter(i => i.status === 'Archived').length;

  // Filter inquiries
  const filteredInquiries = inquiries.filter(inq => {
    const matchesStatus = statusFilter === 'all' || inq.status === statusFilter;
    const q = searchQuery.toLowerCase().trim();
    const matchesSearch = !q ||
      inq.fullName.toLowerCase().includes(q) ||
      inq.email.toLowerCase().includes(q) ||
      inq.phone.toLowerCase().includes(q) ||
      inq.serviceTitle.toLowerCase().includes(q) ||
      inq.referenceCode.toLowerCase().includes(q) ||
      (inq.notes && inq.notes.toLowerCase().includes(q)) ||
      (inq.staffNotes && inq.staffNotes.toLowerCase().includes(q));

    return matchesStatus && matchesSearch;
  });

  // Generate Email Summary Text
  const pendingInquiries = inquiries.filter(i => i.status === 'New' || i.status === 'Contacted');
  
  const generateEmailSummaryText = () => {
    const dateStr = new Date().toLocaleDateString('en-CA', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    const timeStr = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    let body = `HAIR POWER SALON - PENDING CUSTOMER INQUIRIES REPORT\n`;
    body += `Salon: ${salonInfo.name} (565 Dundas St, Woodstock, ON)\n`;
    body += `Report Timestamp: ${dateStr} at ${timeStr}\n`;
    body += `Total Pending Inquiries: ${pendingInquiries.length}\n`;
    body += `=======================================================\n\n`;

    if (pendingInquiries.length === 0) {
      body += `No pending inquiries at this time. All customer inquiries are confirmed or completed.\n\n`;
    } else {
      pendingInquiries.forEach((inq, idx) => {
        const createdDate = new Date(inq.createdAt).toLocaleString('en-US', {
          month: 'short',
          day: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        });

        body += `[${idx + 1}] INQUIRY: ${inq.referenceCode} (Received: ${createdDate})\n`;
        body += `  • Client Name: ${inq.fullName}\n`;
        body += `  • Phone: ${inq.phone}\n`;
        body += `  • Email: ${inq.email}\n`;
        body += `  • Requested Service: ${inq.serviceTitle}\n`;
        body += `  • Preferred Date & Time: ${inq.preferredDate} at ${inq.preferredTime}\n`;
        if (inq.notes) {
          body += `  • Client Notes: "${inq.notes}"\n`;
        }
        if (inq.staffNotes) {
          body += `  • Staff Notes: "${inq.staffNotes}"\n`;
        }
        body += `  • Current Status: ${inq.status.toUpperCase()}\n`;
        body += `-------------------------------------------------------\n\n`;
      });
    }

    body += `Generated by Hair Power Staff Portal • Woodstock, ON\n`;
    body += `Phone: (519) 537-7302\n`;
    return body;
  };

  const summarySubject = `Hair Power Woodstock - Pending Inquiries Summary (${pendingInquiries.length} Pending) - ${new Date().toLocaleDateString('en-CA')}`;
  const summaryBody = generateEmailSummaryText();

  // Email action links
  const mailtoUrl = `mailto:${encodeURIComponent(summaryRecipient)}?subject=${encodeURIComponent(summarySubject)}&body=${encodeURIComponent(summaryBody)}`;
  const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(summaryRecipient)}&su=${encodeURIComponent(summarySubject)}&body=${encodeURIComponent(summaryBody)}`;

  const handleCopySummary = async () => {
    try {
      await navigator.clipboard.writeText(summaryBody);
      setCopiedSummary(true);
      onShowNotification('Summary report copied to clipboard!');
      setTimeout(() => setCopiedSummary(false), 2500);
    } catch {
      onShowNotification('Failed to copy to clipboard.');
    }
  };

  const handleMarkAllPendingAsContacted = () => {
    const updated = inquiries.map(i => {
      if (i.status === 'New') {
        return { ...i, status: 'Contacted' as InquiryStatus };
      }
      return i;
    });
    onUpdateInquiries(updated);
    onShowNotification(`Marked ${newCount} new inquiries as "Contacted"!`);
  };

  // Status changer
  const handleUpdateStatus = (id: string, newStatus: InquiryStatus) => {
    const updated = inquiries.map(i => i.id === id ? { ...i, status: newStatus } : i);
    onUpdateInquiries(updated);
    onShowNotification(`Status updated to "${newStatus}"`);
  };

  // Save staff note
  const handleSaveStaffNote = (id: string) => {
    const updated = inquiries.map(i => i.id === id ? { ...i, staffNotes: staffNoteDraft } : i);
    onUpdateInquiries(updated);
    setEditingStaffNoteId(null);
    setStaffNoteDraft('');
    onShowNotification('Staff internal note saved.');
  };

  // Delete inquiry
  const handleDeleteInquiry = (id: string, refCode: string) => {
    if (window.confirm(`Are you sure you want to delete inquiry ${refCode}?`)) {
      const updated = inquiries.filter(i => i.id !== id);
      onUpdateInquiries(updated);
      onShowNotification(`Inquiry ${refCode} deleted.`);
    }
  };

  // Add manual inquiry
  const handleCreateManualInquiry = (e: React.FormEvent) => {
    e.preventDefault();
    if (!manualForm.fullName.trim() || !manualForm.phone.trim()) {
      alert('Please provide customer name and phone number.');
      return;
    }

    const service = services.find(s => s.id === manualForm.serviceId) || services[0];
    const newRef = 'HP-' + Math.floor(100000 + Math.random() * 900000);

    const created: CustomerInquiry = {
      id: 'inq-' + Date.now(),
      referenceCode: newRef,
      createdAt: new Date().toISOString(),
      type: 'booking',
      fullName: manualForm.fullName.trim(),
      phone: manualForm.phone.trim(),
      email: manualForm.email.trim() || 'No email provided',
      serviceId: manualForm.serviceId,
      serviceTitle: service?.title || 'Hair Service',
      preferredDate: manualForm.preferredDate || 'Walk-in / Scheduled by Phone',
      preferredTime: manualForm.preferredTime || '11:00 AM',
      notes: manualForm.notes.trim(),
      staffNotes: manualForm.staffNotes.trim() || 'Logged manually by staff',
      status: manualForm.status
    };

    onUpdateInquiries([created, ...inquiries]);
    setIsAddManualOpen(false);
    setManualForm({
      fullName: '',
      phone: '',
      email: '',
      serviceId: services[0]?.id || 'womens-cut',
      preferredDate: '',
      preferredTime: '11:00 AM',
      notes: '',
      staffNotes: '',
      status: 'New'
    });
    onShowNotification(`Inquiry ${newRef} logged successfully!`);
  };

  // Export to CSV
  const handleExportCSV = () => {
    const headers = ['Reference Code', 'Date Received', 'Customer Name', 'Phone', 'Email', 'Service', 'Preferred Date', 'Preferred Time', 'Status', 'Customer Notes', 'Staff Notes'];
    const rows = inquiries.map(i => [
      `"${i.referenceCode}"`,
      `"${new Date(i.createdAt).toLocaleString()}"`,
      `"${i.fullName.replace(/"/g, '""')}"`,
      `"${i.phone.replace(/"/g, '""')}"`,
      `"${i.email.replace(/"/g, '""')}"`,
      `"${i.serviceTitle.replace(/"/g, '""')}"`,
      `"${i.preferredDate.replace(/"/g, '""')}"`,
      `"${i.preferredTime.replace(/"/g, '""')}"`,
      `"${i.status}"`,
      `"${(i.notes || '').replace(/"/g, '""')}"`,
      `"${(i.staffNotes || '').replace(/"/g, '""')}"`
    ]);

    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `hairpower_inquiries_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    onShowNotification('Customer inquiries exported to CSV!');
  };

  const getStatusBadge = (status: InquiryStatus) => {
    switch (status) {
      case 'New':
        return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'Contacted':
        return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
      case 'Confirmed':
        return 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30';
      case 'Completed':
        return 'bg-purple-500/20 text-purple-400 border-purple-500/30';
      case 'Archived':
        return 'bg-stone-700/40 text-stone-400 border-stone-600/30';
      default:
        return 'bg-stone-800 text-stone-300 border-stone-700';
    }
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      {/* Top Metrics Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="p-4 bg-stone-900/80 border border-stone-800 rounded-lg">
          <div className="flex items-center justify-between">
            <span className="text-xs text-stone-400 uppercase tracking-wider font-medium">New / Pending</span>
            <span className="p-1.5 bg-amber-500/10 text-amber-400 rounded-full">
              <Icon name="solar:bell-bing-bold" className="text-lg" />
            </span>
          </div>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="text-3xl font-serif font-bold text-amber-400">{newCount}</span>
            <span className="text-xs text-stone-500">needs response</span>
          </div>
        </div>

        <div className="p-4 bg-stone-900/80 border border-stone-800 rounded-lg">
          <div className="flex items-center justify-between">
            <span className="text-xs text-stone-400 uppercase tracking-wider font-medium">Contacted</span>
            <span className="p-1.5 bg-blue-500/10 text-blue-400 rounded-full">
              <Icon name="solar:phone-calling-linear" className="text-lg" />
            </span>
          </div>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="text-3xl font-serif font-bold text-blue-400">{contactedCount}</span>
            <span className="text-xs text-stone-500">in progress</span>
          </div>
        </div>

        <div className="p-4 bg-stone-900/80 border border-stone-800 rounded-lg">
          <div className="flex items-center justify-between">
            <span className="text-xs text-stone-400 uppercase tracking-wider font-medium">Confirmed</span>
            <span className="p-1.5 bg-emerald-500/10 text-emerald-400 rounded-full">
              <Icon name="solar:calendar-check-bold" className="text-lg" />
            </span>
          </div>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="text-3xl font-serif font-bold text-emerald-400">{confirmedCount}</span>
            <span className="text-xs text-stone-500">booked appointments</span>
          </div>
        </div>

        <div className="p-4 bg-stone-900/80 border border-stone-800 rounded-lg">
          <div className="flex items-center justify-between">
            <span className="text-xs text-stone-400 uppercase tracking-wider font-medium">Total Inquiries</span>
            <span className="p-1.5 bg-[#C5A065]/10 text-[#C5A065] rounded-full">
              <Icon name="solar:users-group-two-rounded-linear" className="text-lg" />
            </span>
          </div>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="text-3xl font-serif font-bold text-stone-100">{totalCount}</span>
            <span className="text-xs text-stone-500">all time</span>
          </div>
        </div>
      </div>

      {/* Action Banner: Trigger Summary Email & Tools */}
      <div className="p-5 bg-gradient-to-r from-stone-900 via-stone-900/90 to-[#C5A065]/10 border border-[#C5A065]/30 rounded-lg flex flex-wrap items-center justify-between gap-4 shadow-lg">
        <div className="flex items-center gap-3.5">
          <div className="w-12 h-12 bg-[#C5A065] text-stone-950 rounded-lg flex items-center justify-center shadow-md shrink-0">
            <Icon name="solar:letter-unread-bold" className="text-2xl" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-serif text-base text-white font-semibold tracking-wide">
                Summary Email Notification
              </h3>
              <span className="px-2 py-0.5 bg-[#C5A065]/20 text-[#C5A065] text-[10px] font-bold uppercase rounded border border-[#C5A065]/30">
                Staff Feature
              </span>
            </div>
            <p className="text-xs text-stone-400 mt-0.5">
              Generate & trigger a comprehensive summary report of all pending inquiries to <strong className="text-amber-300 font-mono">kevfun73@gmail.com</strong>
            </p>
          </div>
        </div>

        <div className="flex items-center flex-wrap gap-2.5">
          <button
            onClick={() => setIsSummaryModalOpen(true)}
            className="px-4 py-2.5 bg-[#C5A065] hover:bg-[#b58f55] text-stone-950 font-semibold text-xs uppercase tracking-wider rounded transition-all flex items-center gap-2 shadow-md hover:scale-[1.02]"
          >
            <Icon name="solar:plain-bold" className="text-base" />
            <span>Trigger Summary Email ({pendingInquiries.length})</span>
          </button>

          <button
            onClick={() => setIsAddManualOpen(true)}
            className="px-3.5 py-2.5 bg-stone-800 hover:bg-stone-700 text-stone-200 text-xs font-medium uppercase tracking-wider rounded transition-colors flex items-center gap-1.5 border border-stone-700"
          >
            <Icon name="solar:user-plus-linear" className="text-base text-[#C5A065]" />
            <span>Log Call / Walk-In</span>
          </button>

          <button
            onClick={handleExportCSV}
            className="px-3 py-2.5 bg-stone-800 hover:bg-stone-700 text-stone-300 text-xs font-medium uppercase tracking-wider rounded transition-colors flex items-center gap-1.5 border border-stone-700"
            title="Download CSV spreadsheet"
          >
            <Icon name="solar:file-download-linear" className="text-base" />
            <span>CSV</span>
          </button>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col md:flex-row gap-3 justify-between items-stretch md:items-center bg-stone-900/60 p-3 rounded-lg border border-stone-800">
        {/* Status Filters */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 md:pb-0">
          <button
            onClick={() => setStatusFilter('all')}
            className={`px-3 py-1.5 rounded text-xs font-medium transition-colors whitespace-nowrap ${
              statusFilter === 'all'
                ? 'bg-[#C5A065] text-stone-950 font-semibold shadow-sm'
                : 'bg-stone-800/80 text-stone-400 hover:text-stone-200'
            }`}
          >
            All ({totalCount})
          </button>

          <button
            onClick={() => setStatusFilter('New')}
            className={`px-3 py-1.5 rounded text-xs font-medium transition-colors whitespace-nowrap flex items-center gap-1.5 ${
              statusFilter === 'New'
                ? 'bg-amber-500 text-stone-950 font-semibold shadow-sm'
                : 'bg-stone-800/80 text-amber-400/80 hover:text-amber-300'
            }`}
          >
            <span className="w-2 h-2 rounded-full bg-amber-400 animate-pulse"></span>
            <span>New ({newCount})</span>
          </button>

          <button
            onClick={() => setStatusFilter('Contacted')}
            className={`px-3 py-1.5 rounded text-xs font-medium transition-colors whitespace-nowrap ${
              statusFilter === 'Contacted'
                ? 'bg-blue-500 text-white font-semibold shadow-sm'
                : 'bg-stone-800/80 text-stone-400 hover:text-blue-300'
            }`}
          >
            Contacted ({contactedCount})
          </button>

          <button
            onClick={() => setStatusFilter('Confirmed')}
            className={`px-3 py-1.5 rounded text-xs font-medium transition-colors whitespace-nowrap ${
              statusFilter === 'Confirmed'
                ? 'bg-emerald-600 text-white font-semibold shadow-sm'
                : 'bg-stone-800/80 text-stone-400 hover:text-emerald-300'
            }`}
          >
            Confirmed ({confirmedCount})
          </button>

          <button
            onClick={() => setStatusFilter('Completed')}
            className={`px-3 py-1.5 rounded text-xs font-medium transition-colors whitespace-nowrap ${
              statusFilter === 'Completed'
                ? 'bg-purple-600 text-white font-semibold shadow-sm'
                : 'bg-stone-800/80 text-stone-400 hover:text-purple-300'
            }`}
          >
            Completed ({completedCount})
          </button>

          <button
            onClick={() => setStatusFilter('Archived')}
            className={`px-3 py-1.5 rounded text-xs font-medium transition-colors whitespace-nowrap ${
              statusFilter === 'Archived'
                ? 'bg-stone-700 text-white font-semibold shadow-sm'
                : 'bg-stone-800/80 text-stone-400 hover:text-stone-300'
            }`}
          >
            Archived ({archivedCount})
          </button>
        </div>

        {/* Search Input */}
        <div className="relative min-w-[240px]">
          <Icon name="solar:magnifer-linear" className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500 text-sm" />
          <input
            type="text"
            placeholder="Search by client, phone, service, ref..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 bg-stone-950 border border-stone-700 rounded text-xs text-stone-100 placeholder-stone-500 focus:outline-none focus:border-[#C5A065]"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-2.5 top-1/2 -translate-y-1/2 text-stone-500 hover:text-stone-300 text-xs"
            >
              ✕
            </button>
          )}
        </div>
      </div>

      {/* Inquiries List */}
      <div className="space-y-3.5">
        {filteredInquiries.length === 0 ? (
          <div className="p-12 text-center bg-stone-900/40 border border-dashed border-stone-800 rounded-lg">
            <div className="w-12 h-12 mx-auto bg-stone-800 rounded-full flex items-center justify-center text-stone-500 mb-3">
              <Icon name="solar:inbox-linear" className="text-2xl" />
            </div>
            <h4 className="font-serif text-sm text-stone-300 font-medium">No inquiries found</h4>
            <p className="text-xs text-stone-500 mt-1">
              {searchQuery ? 'Try clearing your search filters.' : 'New customer inquiries from the website will automatically appear here.'}
            </p>
            {searchQuery && (
              <button
                onClick={() => { setSearchQuery(''); setStatusFilter('all'); }}
                className="mt-3 px-3 py-1.5 bg-stone-800 text-stone-300 text-xs rounded hover:bg-stone-700"
              >
                Reset Search
              </button>
            )}
          </div>
        ) : (
          filteredInquiries.map((inq) => {
            const formattedDate = new Date(inq.createdAt).toLocaleDateString('en-US', {
              month: 'short',
              day: 'numeric',
              year: 'numeric'
            });
            const formattedTime = new Date(inq.createdAt).toLocaleTimeString('en-US', {
              hour: '2-digit',
              minute: '2-digit'
            });

            const isEditingNote = editingStaffNoteId === inq.id;

            return (
              <div
                key={inq.id}
                className={`p-5 bg-stone-900/70 border rounded-lg transition-all ${
                  inq.status === 'New'
                    ? 'border-amber-500/40 shadow-sm bg-stone-900/90'
                    : 'border-stone-800 hover:border-stone-700'
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4">
                  {/* Left Column: Customer & Request Details */}
                  <div className="space-y-3 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-mono text-xs font-bold px-2 py-0.5 bg-[#C5A065]/10 text-[#C5A065] rounded border border-[#C5A065]/20">
                        {inq.referenceCode}
                      </span>
                      <span className={`text-[11px] font-semibold px-2 py-0.5 rounded border ${getStatusBadge(inq.status)}`}>
                        {inq.status}
                      </span>
                      <span className="text-xs text-stone-500">
                        Received {formattedDate} at {formattedTime}
                      </span>
                    </div>

                    <div className="flex flex-wrap items-center gap-x-6 gap-y-2 pt-1">
                      <div className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-full bg-[#C5A065]/20 text-[#C5A065] flex items-center justify-center font-serif font-bold text-sm">
                          {inq.fullName.charAt(0) || 'C'}
                        </div>
                        <div>
                          <h4 className="font-medium text-sm text-white font-serif">{inq.fullName}</h4>
                          <span className="text-[11px] text-stone-400">Customer</span>
                        </div>
                      </div>

                      {/* Contact Channels */}
                      <div className="flex items-center gap-2">
                        <a
                          href={`tel:${inq.phone.replace(/[^0-9+]/g, '')}`}
                          className="px-2.5 py-1 bg-stone-800 hover:bg-emerald-950 hover:text-emerald-400 text-stone-300 text-xs rounded transition-colors flex items-center gap-1.5 border border-stone-700"
                          title="Call Customer"
                        >
                          <Icon name="solar:phone-calling-linear" className="text-sm text-emerald-400" />
                          <span>{inq.phone}</span>
                        </a>

                        {inq.email && inq.email !== 'No email provided' && (
                          <a
                            href={`mailto:${inq.email}?subject=${encodeURIComponent(`Hair Power Appointment Inquiry (${inq.referenceCode})`)}`}
                            className="px-2.5 py-1 bg-stone-800 hover:bg-blue-950 hover:text-blue-400 text-stone-300 text-xs rounded transition-colors flex items-center gap-1.5 border border-stone-700"
                            title="Email Customer"
                          >
                            <Icon name="solar:letter-linear" className="text-sm text-blue-400" />
                            <span>{inq.email}</span>
                          </a>
                        )}

                        <a
                          href={`https://wa.me/${inq.phone.replace(/[^0-9]/g, '')}?text=${encodeURIComponent(`Hello ${inq.fullName}! This is Frank from Hair Power salon in Woodstock regarding your booking inquiry (${inq.referenceCode}).`)}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="p-1.5 bg-[#25D366]/20 hover:bg-[#25D366] text-[#25D366] hover:text-white rounded transition-colors"
                          title="WhatsApp Chat"
                        >
                          <Icon name="solar:chat-round-dots-linear" className="text-sm" />
                        </a>
                      </div>
                    </div>

                    {/* Service & Preferred Date */}
                    <div className="grid sm:grid-cols-2 gap-3 p-3 bg-stone-950/60 rounded border border-stone-800/80 text-xs">
                      <div>
                        <span className="text-stone-500 uppercase text-[10px] tracking-wider block">Requested Service:</span>
                        <span className="font-semibold text-stone-200 mt-0.5 block text-sm">{inq.serviceTitle}</span>
                      </div>
                      <div>
                        <span className="text-stone-500 uppercase text-[10px] tracking-wider block">Preferred Date & Time:</span>
                        <span className="font-medium text-[#C5A065] mt-0.5 block">
                          📅 {inq.preferredDate} • ⏰ {inq.preferredTime}
                        </span>
                      </div>
                    </div>

                    {/* Customer Notes */}
                    {inq.notes && (
                      <div className="p-3 bg-stone-950/40 rounded border-l-2 border-[#C5A065] text-xs">
                        <span className="text-stone-400 font-medium block text-[11px] mb-0.5">Client Note / Message:</span>
                        <p className="text-stone-300 italic">"{inq.notes}"</p>
                      </div>
                    )}

                    {/* Staff Notes Section */}
                    <div className="pt-1">
                      {isEditingNote ? (
                        <div className="space-y-2">
                          <label className="text-[11px] text-stone-400 uppercase tracking-wider font-medium block">
                            Internal Staff Notes:
                          </label>
                          <textarea
                            rows={2}
                            value={staffNoteDraft}
                            onChange={e => setStaffNoteDraft(e.target.value)}
                            placeholder="Add internal notes (e.g. Frank confirmed for 11am, deposit received, etc.)..."
                            className="w-full px-3 py-1.5 bg-stone-950 border border-stone-700 rounded text-xs text-stone-100 focus:outline-none focus:border-[#C5A065]"
                          />
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handleSaveStaffNote(inq.id)}
                              className="px-3 py-1 bg-[#C5A065] text-stone-950 text-xs font-semibold rounded hover:bg-[#b58f55]"
                            >
                              Save Note
                            </button>
                            <button
                              onClick={() => { setEditingStaffNoteId(null); setStaffNoteDraft(''); }}
                              className="px-3 py-1 bg-stone-800 text-stone-400 text-xs rounded hover:bg-stone-700"
                            >
                              Cancel
                            </button>
                          </div>
                        </div>
                      ) : (
                        <div className="flex items-start justify-between gap-2 p-2.5 bg-stone-950/30 rounded border border-stone-800/60 text-xs">
                          <div>
                            <span className="text-[10px] uppercase text-stone-500 tracking-wider font-semibold block">Staff Internal Note:</span>
                            <p className="text-stone-300 text-xs mt-0.5">
                              {inq.staffNotes || <span className="text-stone-500 italic">No internal staff notes yet.</span>}
                            </p>
                          </div>
                          <button
                            onClick={() => {
                              setEditingStaffNoteId(inq.id);
                              setStaffNoteDraft(inq.staffNotes || '');
                            }}
                            className="text-[11px] text-[#C5A065] hover:underline shrink-0 font-medium"
                          >
                            {inq.staffNotes ? 'Edit' : '+ Add Note'}
                          </button>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Right Column: Status Selector & Actions */}
                  <div className="flex lg:flex-col items-center lg:items-end justify-between gap-3 pt-3 lg:pt-0 border-t lg:border-t-0 border-stone-800 shrink-0">
                    <div className="flex flex-col items-start lg:items-end gap-1">
                      <span className="text-[10px] uppercase text-stone-500 font-semibold tracking-wider">Update Status:</span>
                      <select
                        value={inq.status}
                        onChange={e => handleUpdateStatus(inq.id, e.target.value as InquiryStatus)}
                        className="px-3 py-1.5 bg-stone-950 border border-stone-700 text-xs font-semibold rounded text-stone-200 focus:outline-none focus:border-[#C5A065]"
                      >
                        <option value="New">🟡 New (Pending)</option>
                        <option value="Contacted">🔵 Contacted</option>
                        <option value="Confirmed">🟢 Confirmed</option>
                        <option value="Completed">🟣 Completed</option>
                        <option value="Archived">⚪ Archived</option>
                      </select>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleDeleteInquiry(inq.id, inq.referenceCode)}
                        className="p-1.5 text-stone-500 hover:text-red-400 hover:bg-red-950/40 rounded transition-colors"
                        title="Delete Inquiry"
                      >
                        <Icon name="solar:trash-bin-trash-linear" className="text-base" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* SUMMARY EMAIL MODAL / PREVIEW DIALOG */}
      {isSummaryModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-950/80 backdrop-blur-sm animate-fadeIn">
          <div className="bg-[#1C1917] border border-stone-700 rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col overflow-hidden">
            {/* Modal Header */}
            <div className="px-6 py-4 bg-stone-900 border-b border-stone-800 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 bg-[#C5A065] text-stone-950 rounded flex items-center justify-center font-bold">
                  <Icon name="solar:letter-unread-bold" className="text-xl" />
                </div>
                <div>
                  <h3 className="font-serif text-base font-semibold text-white">
                    Pending Inquiries Email Summary
                  </h3>
                  <p className="text-xs text-stone-400">
                    Ready to send to <strong className="text-amber-300 font-mono">{summaryRecipient}</strong>
                  </p>
                </div>
              </div>
              <button
                onClick={() => setIsSummaryModalOpen(false)}
                className="text-stone-400 hover:text-white p-1"
              >
                <Icon name="solar:close-circle-linear" className="text-2xl" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="p-6 overflow-y-auto space-y-4 flex-1">
              {/* Recipient Field */}
              <div>
                <label className="block text-xs uppercase tracking-wider text-stone-400 font-medium mb-1">
                  Recipient Email:
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="email"
                    value={summaryRecipient}
                    onChange={e => setSummaryRecipient(e.target.value)}
                    className="flex-1 px-3 py-2 bg-stone-950 border border-stone-700 rounded text-xs text-stone-100 font-mono focus:outline-none focus:border-[#C5A065]"
                  />
                  <button
                    onClick={() => setSummaryRecipient(TARGET_EMAIL)}
                    className="px-2.5 py-2 bg-stone-800 hover:bg-stone-700 text-stone-300 text-xs rounded"
                    title="Reset to default requested address"
                  >
                    Reset (kevfun73@gmail.com)
                  </button>
                </div>
              </div>

              {/* Subject */}
              <div>
                <label className="block text-xs uppercase tracking-wider text-stone-400 font-medium mb-1">
                  Email Subject:
                </label>
                <input
                  type="text"
                  readOnly
                  value={summarySubject}
                  className="w-full px-3 py-2 bg-stone-950 border border-stone-800 rounded text-xs text-stone-300 focus:outline-none"
                />
              </div>

              {/* Email Content Preview */}
              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="block text-xs uppercase tracking-wider text-stone-400 font-medium">
                    Formatted Summary Report Content ({pendingInquiries.length} pending):
                  </label>
                  <button
                    onClick={handleCopySummary}
                    className="text-xs text-[#C5A065] hover:underline flex items-center gap-1 font-medium"
                  >
                    <Icon name={copiedSummary ? 'solar:check-circle-bold' : 'solar:copy-linear'} className="text-sm" />
                    <span>{copiedSummary ? 'Copied!' : 'Copy to Clipboard'}</span>
                  </button>
                </div>
                <pre className="w-full p-4 bg-stone-950 border border-stone-800 rounded text-[11px] text-stone-300 font-mono overflow-x-auto whitespace-pre-wrap max-h-60 leading-relaxed">
                  {summaryBody}
                </pre>
              </div>

              {/* Status Update Quick Action */}
              {newCount > 0 && (
                <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded flex items-center justify-between gap-3 text-xs">
                  <span className="text-amber-200">
                    💡 You have {newCount} inquiry marked as <strong>New</strong>. Would you like to mark them as <strong>Contacted</strong> after sending?
                  </span>
                  <button
                    onClick={handleMarkAllPendingAsContacted}
                    className="px-3 py-1.5 bg-amber-500 text-stone-950 font-semibold rounded hover:bg-amber-400 text-xs shrink-0"
                  >
                    Mark as Contacted
                  </button>
                </div>
              )}
            </div>

            {/* Modal Footer Actions */}
            <div className="px-6 py-4 bg-stone-900 border-t border-stone-800 flex flex-wrap items-center justify-between gap-3">
              <button
                onClick={handleCopySummary}
                className="px-4 py-2 bg-stone-800 hover:bg-stone-700 text-stone-200 text-xs font-semibold uppercase tracking-wider rounded transition-colors flex items-center gap-1.5"
              >
                <Icon name={copiedSummary ? 'solar:check-circle-bold' : 'solar:copy-linear'} className="text-base text-[#C5A065]" />
                <span>{copiedSummary ? 'Copied to Clipboard' : 'Copy Report'}</span>
              </button>

              <div className="flex items-center gap-2">
                <a
                  href={gmailUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={() => onShowNotification(`Opening Gmail composer for ${summaryRecipient}...`)}
                  className="px-4 py-2 bg-red-600/90 hover:bg-red-600 text-white text-xs font-semibold uppercase tracking-wider rounded transition-colors flex items-center gap-1.5 shadow"
                >
                  <Icon name="solar:letter-bold" className="text-base" />
                  <span>Open in Gmail</span>
                </a>

                <a
                  href={mailtoUrl}
                  onClick={() => onShowNotification(`Triggering email client for ${summaryRecipient}...`)}
                  className="px-4 py-2 bg-[#C5A065] hover:bg-[#b58f55] text-stone-950 text-xs font-bold uppercase tracking-wider rounded transition-all flex items-center gap-1.5 shadow-md"
                >
                  <Icon name="solar:plain-bold" className="text-base" />
                  <span>Send via Mail App</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ADD MANUAL INQUIRY MODAL */}
      {isAddManualOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-950/80 backdrop-blur-sm animate-fadeIn">
          <div className="bg-[#1C1917] border border-stone-700 rounded-xl shadow-2xl max-w-lg w-full max-h-[90vh] flex flex-col overflow-hidden">
            <div className="px-6 py-4 bg-stone-900 border-b border-stone-800 flex items-center justify-between">
              <h3 className="font-serif text-base font-semibold text-white flex items-center gap-2">
                <Icon name="solar:user-plus-linear" className="text-[#C5A065]" />
                <span>Log Phone or Walk-In Booking</span>
              </h3>
              <button onClick={() => setIsAddManualOpen(false)} className="text-stone-400 hover:text-white">
                <Icon name="solar:close-circle-linear" className="text-2xl" />
              </button>
            </div>

            <form onSubmit={handleCreateManualInquiry} className="p-6 overflow-y-auto space-y-4 flex-1 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Customer Name *</label>
                  <input
                    type="text"
                    required
                    value={manualForm.fullName}
                    onChange={e => setManualForm({ ...manualForm, fullName: e.target.value })}
                    placeholder="e.g. Rachel Adams"
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  />
                </div>

                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Phone Number *</label>
                  <input
                    type="tel"
                    required
                    value={manualForm.phone}
                    onChange={e => setManualForm({ ...manualForm, phone: e.target.value })}
                    placeholder="(519) 555-0199"
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Email Address</label>
                  <input
                    type="email"
                    value={manualForm.email}
                    onChange={e => setManualForm({ ...manualForm, email: e.target.value })}
                    placeholder="optional@example.com"
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  />
                </div>

                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Requested Service</label>
                  <select
                    value={manualForm.serviceId}
                    onChange={e => setManualForm({ ...manualForm, serviceId: e.target.value })}
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  >
                    {services.map(s => (
                      <option key={s.id} value={s.id}>{s.title} ({s.price})</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Preferred Date</label>
                  <input
                    type="date"
                    value={manualForm.preferredDate}
                    onChange={e => setManualForm({ ...manualForm, preferredDate: e.target.value })}
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  />
                </div>

                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Preferred Time</label>
                  <input
                    type="text"
                    value={manualForm.preferredTime}
                    onChange={e => setManualForm({ ...manualForm, preferredTime: e.target.value })}
                    placeholder="e.g. 11:00 AM"
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  />
                </div>
              </div>

              <div>
                <label className="block uppercase text-stone-400 font-medium mb-1">Customer Request Details</label>
                <textarea
                  rows={2}
                  value={manualForm.notes}
                  onChange={e => setManualForm({ ...manualForm, notes: e.target.value })}
                  placeholder="Hair texture, desired color, bridal party notes, etc..."
                  className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Initial Status</label>
                  <select
                    value={manualForm.status}
                    onChange={e => setManualForm({ ...manualForm, status: e.target.value as InquiryStatus })}
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  >
                    <option value="New">New (Pending)</option>
                    <option value="Contacted">Contacted</option>
                    <option value="Confirmed">Confirmed</option>
                  </select>
                </div>

                <div>
                  <label className="block uppercase text-stone-400 font-medium mb-1">Staff Note</label>
                  <input
                    type="text"
                    value={manualForm.staffNotes}
                    onChange={e => setManualForm({ ...manualForm, staffNotes: e.target.value })}
                    placeholder="e.g. Phone booking taken by Frank"
                    className="w-full px-3 py-2 bg-stone-950 border border-stone-700 rounded text-stone-100 focus:outline-none focus:border-[#C5A065]"
                  />
                </div>
              </div>

              <div className="pt-4 border-t border-stone-800 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setIsAddManualOpen(false)}
                  className="px-4 py-2 bg-stone-800 text-stone-300 rounded hover:bg-stone-700"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-[#C5A065] text-stone-950 font-semibold uppercase tracking-wider rounded hover:bg-[#b58f55]"
                >
                  Save Inquiry
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
